/******************************************************************************
**
** <auto-generated>
**     This code was generated by a tool: UaModeler
**     Runtime Version: 1.6.5, using .NET Server 2.6.0 template (version 2)
**
**     Changes to this file may cause incorrect behavior and will be lost if
**     the code is regenerated.
**
**     Generated by Dr. Matthias Arnold <M.Arnold@AixEngineers.de>
** </auto-generated>
**
** Copyright (c) 2006-2022 Unified Automation GmbH All rights reserved.
**
** Software License Agreement ("SLA") Version 2.7
**
** Unless explicitly acquired and licensed from Licensor under another
** license, the contents of this file are subject to the Software License
** Agreement ("SLA") Version 2.7, or subsequent versions
** as allowed by the SLA, and You may not copy or use this file in either
** source code or executable form, except in compliance with the terms and
** conditions of the SLA.
**
** All software distributed under the SLA is provided strictly on an
** "AS IS" basis, WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED,
** AND LICENSOR HEREBY DISCLAIMS ALL SUCH WARRANTIES, INCLUDING WITHOUT
** LIMITATION, ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
** PURPOSE, QUIET ENJOYMENT, OR NON-INFRINGEMENT. See the SLA for specific
** language governing rights and limitations under the SLA.
**
** Project: .NET OPC UA SDK information model for namespace http://opcfoundation.org/UA/Machinery/
**
** Description: OPC Unified Architecture Software Development Kit.
**
** The complete license agreement can be found here:
** http://unifiedautomation.com/License/SLA/2.7/
**
** Created: 01.04.2022
**
******************************************************************************/

using System;
using System.Collections.Generic;
using System.Text;
using System.Reflection;
using System.Xml;
using System.Runtime.Serialization;
using Opc.Ua;
#pragma warning disable CS1570

namespace OPCF.Machinery
{
    #region DataType Identifiers
    /// <summary>
    /// A class that declares constants for all DataTypes in the Model.
    /// </summary>

    public static partial class DataTypes
    {
    }
    #endregion

    #region Object Identifiers
    /// <summary>
    /// A class that declares constants for all Objects in the Model.
    /// </summary>

    public static partial class Objects
    {
        /// <summary>
        /// The identifier for the <Component> Object.
        /// </summary>
        public const uint MachineComponentsType_Component = 5002;

        /// <summary>
        /// The identifier for the Identification Object.
        /// </summary>
        public const uint MachineComponentsType_Component_Identification = 5003;

        /// <summary>
        /// The identifier for the Machines Object.
        /// </summary>
        public const uint Machines = 1001;

        /// <summary>
        /// The identifier for the http://opcfoundation.org/UA/Machinery/ Object.
        /// </summary>
        public const uint Namespaces_http___opcfoundation_org_UA_Machinery_ = 5001;

    }
    #endregion

    #region ObjectType Identifiers
    /// <summary>
    /// A class that declares constants for all ObjectTypes in the Model.
    /// </summary>

    public static partial class ObjectTypes
    {
        /// <summary>
        /// The identifier for the IMachineTagNameplateType ObjectType.
        /// </summary>
        public const uint IMachineTagNameplateType = 1011;

        /// <summary>
        /// The identifier for the IMachineryItemVendorNameplateType ObjectType.
        /// </summary>
        public const uint IMachineryItemVendorNameplateType = 1003;

        /// <summary>
        /// The identifier for the IMachineVendorNameplateType ObjectType.
        /// </summary>
        public const uint IMachineVendorNameplateType = 1010;

        /// <summary>
        /// The identifier for the MachineryItemIdentificationType ObjectType.
        /// </summary>
        public const uint MachineryItemIdentificationType = 1004;

        /// <summary>
        /// The identifier for the MachineIdentificationType ObjectType.
        /// </summary>
        public const uint MachineIdentificationType = 1012;

        /// <summary>
        /// The identifier for the MachineryComponentIdentificationType ObjectType.
        /// </summary>
        public const uint MachineryComponentIdentificationType = 1005;

        /// <summary>
        /// The identifier for the MachineComponentsType ObjectType.
        /// </summary>
        public const uint MachineComponentsType = 1006;

    }
    #endregion

    #region Method Identifiers
    /// <summary>
    /// A class that declares constants for all Methods in the Model.
    /// </summary>

    public static partial class Methods
    {
    }
    #endregion

    #region ReferenceType Identifiers
    /// <summary>
    /// A class that declares constants for all ReferenceTyped in the Model.
    /// </summary>

    public static partial class ReferenceTypes
    {
    }
    #endregion

    #region Variable Identifiers
    /// <summary>
    /// A class that declares constants for all Variables in the Model.
    /// </summary>

    public static partial class Variables
    {
        /// <summary>
        /// The identifier for the Location Variable.
        /// </summary>
        public const uint IMachineTagNameplateType_Location = 6028;

        /// <summary>
        /// The identifier for the ProductInstanceUri Variable.
        /// </summary>
        public const uint IMachineVendorNameplateType_ProductInstanceUri = 6023;

        /// <summary>
        /// The identifier for the InitialOperationDate Variable.
        /// </summary>
        public const uint IMachineryItemVendorNameplateType_InitialOperationDate = 6027;

        /// <summary>
        /// The identifier for the Manufacturer Variable.
        /// </summary>
        public const uint IMachineryItemVendorNameplateType_Manufacturer = 6022;

        /// <summary>
        /// The identifier for the MonthOfConstruction Variable.
        /// </summary>
        public const uint IMachineryItemVendorNameplateType_MonthOfConstruction = 6026;

        /// <summary>
        /// The identifier for the SerialNumber Variable.
        /// </summary>
        public const uint IMachineryItemVendorNameplateType_SerialNumber = 6024;

        /// <summary>
        /// The identifier for the YearOfConstruction Variable.
        /// </summary>
        public const uint IMachineryItemVendorNameplateType_YearOfConstruction = 6025;

        /// <summary>
        /// The identifier for the AssetId Variable.
        /// </summary>
        public const uint MachineryItemIdentificationType_AssetId = 6013;

        /// <summary>
        /// The identifier for the ComponentName Variable.
        /// </summary>
        public const uint MachineryItemIdentificationType_ComponentName = 6014;

        /// <summary>
        /// The identifier for the DeviceClass Variable.
        /// </summary>
        public const uint MachineryItemIdentificationType_DeviceClass = 6012;

        /// <summary>
        /// The identifier for the HardwareRevision Variable.
        /// </summary>
        public const uint MachineryItemIdentificationType_HardwareRevision = 6010;

        /// <summary>
        /// The identifier for the InitialOperationDate Variable.
        /// </summary>
        public const uint MachineryItemIdentificationType_InitialOperationDate = 6006;

        /// <summary>
        /// The identifier for the DefaultInstanceBrowseName Variable.
        /// </summary>
        public const uint MachineIdentificationType_DefaultInstanceBrowseName = 6030;

        /// <summary>
        /// The identifier for the Location Variable.
        /// </summary>
        public const uint MachineIdentificationType_Location = 6029;

        /// <summary>
        /// The identifier for the ProductInstanceUri Variable.
        /// </summary>
        public const uint MachineIdentificationType_ProductInstanceUri = 6015;

        /// <summary>
        /// The identifier for the DefaultInstanceBrowseName Variable.
        /// </summary>
        public const uint MachineryComponentIdentificationType_DefaultInstanceBrowseName = 6016;

        /// <summary>
        /// The identifier for the DeviceRevision Variable.
        /// </summary>
        public const uint MachineryComponentIdentificationType_DeviceRevision = 6017;

        /// <summary>
        /// The identifier for the Manufacturer Variable.
        /// </summary>
        public const uint MachineryItemIdentificationType_Manufacturer = 6002;

        /// <summary>
        /// The identifier for the ManufacturerUri Variable.
        /// </summary>
        public const uint MachineryItemIdentificationType_ManufacturerUri = 6007;

        /// <summary>
        /// The identifier for the Model Variable.
        /// </summary>
        public const uint MachineryItemIdentificationType_Model = 6008;

        /// <summary>
        /// The identifier for the MonthOfConstruction Variable.
        /// </summary>
        public const uint MachineryItemIdentificationType_MonthOfConstruction = 6005;

        /// <summary>
        /// The identifier for the ProductCode Variable.
        /// </summary>
        public const uint MachineryItemIdentificationType_ProductCode = 6009;

        /// <summary>
        /// The identifier for the ProductInstanceUri Variable.
        /// </summary>
        public const uint MachineryItemIdentificationType_ProductInstanceUri = 6001;

        /// <summary>
        /// The identifier for the SerialNumber Variable.
        /// </summary>
        public const uint MachineryItemIdentificationType_SerialNumber = 6003;

        /// <summary>
        /// The identifier for the SoftwareRevision Variable.
        /// </summary>
        public const uint MachineryItemIdentificationType_SoftwareRevision = 6011;

        /// <summary>
        /// The identifier for the YearOfConstruction Variable.
        /// </summary>
        public const uint MachineryItemIdentificationType_YearOfConstruction = 6004;

        /// <summary>
        /// The identifier for the Manufacturer Variable.
        /// </summary>
        public const uint MachineComponentsType_Component_Identification_Manufacturer = 6019;

        /// <summary>
        /// The identifier for the SerialNumber Variable.
        /// </summary>
        public const uint MachineComponentsType_Component_Identification_SerialNumber = 6020;

        /// <summary>
        /// The identifier for the DefaultInstanceBrowseName Variable.
        /// </summary>
        public const uint MachineComponentsType_DefaultInstanceBrowseName = 6018;

        /// <summary>
        /// The identifier for the IsNamespaceSubset Object.
        /// </summary>
        public const uint Namespaces_http___opcfoundation_org_UA_Machinery__IsNamespaceSubset = 6031;

        /// <summary>
        /// The identifier for the NamespacePublicationDate Object.
        /// </summary>
        public const uint Namespaces_http___opcfoundation_org_UA_Machinery__NamespacePublicationDate = 6032;

        /// <summary>
        /// The identifier for the NamespaceUri Object.
        /// </summary>
        public const uint Namespaces_http___opcfoundation_org_UA_Machinery__NamespaceUri = 6033;

        /// <summary>
        /// The identifier for the NamespaceVersion Object.
        /// </summary>
        public const uint Namespaces_http___opcfoundation_org_UA_Machinery__NamespaceVersion = 6034;

        /// <summary>
        /// The identifier for the StaticNodeIdTypes Object.
        /// </summary>
        public const uint Namespaces_http___opcfoundation_org_UA_Machinery__StaticNodeIdTypes = 6035;

        /// <summary>
        /// The identifier for the StaticNumericNodeIdRange Object.
        /// </summary>
        public const uint Namespaces_http___opcfoundation_org_UA_Machinery__StaticNumericNodeIdRange = 6036;

        /// <summary>
        /// The identifier for the StaticStringNodeIdPattern Object.
        /// </summary>
        public const uint Namespaces_http___opcfoundation_org_UA_Machinery__StaticStringNodeIdPattern = 6037;

    }
    #endregion

    #region VariableTypes Identifiers
    /// <summary>
    /// A class that declares constants for all VariableTypes in the Model.
    /// </summary>

    public static partial class VariableTypes
    {
    }
    #endregion

    #region DataType Node Identifiers
    /// <summary>
    /// A class that declares constants for all DataTypes in the Model.
    /// </summary>

    public static partial class DataTypeIds
    {
    }
    #endregion

    #region Method Node Identifiers
    /// <summary>
    /// A class that declares constants for all Methods in the Model.
    /// </summary>

    public static partial class MethodIds
    {
    }
    #endregion

    #region Object Node Identifiers
    /// <summary>
    /// A class that declares constants for all Objects in the Model.
    /// </summary>

    public static partial class ObjectIds
    {
        /// <summary>
        /// The identifier for the MachineComponentsType_Component Object.
        /// </summary>
        public static readonly ExpandedNodeId MachineComponentsType_Component = new ExpandedNodeId(Objects.MachineComponentsType_Component, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineComponentsType_Component_Identification Object.
        /// </summary>
        public static readonly ExpandedNodeId MachineComponentsType_Component_Identification = new ExpandedNodeId(Objects.MachineComponentsType_Component_Identification, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the Machines Object.
        /// </summary>
        public static readonly ExpandedNodeId Machines = new ExpandedNodeId(Objects.Machines, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the Namespaces_http___opcfoundation_org_UA_Machinery_ Object.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___opcfoundation_org_UA_Machinery_ = new ExpandedNodeId(Objects.Namespaces_http___opcfoundation_org_UA_Machinery_, Namespaces.Machinery);

    }
    #endregion

    #region ObjectType Node Identifiers
    /// <summary>
    /// A class that declares constants for all Objects in the Model.
    /// </summary>

    public static partial class ObjectTypeIds
    {
        /// <summary>
        /// The identifier for the IMachineTagNameplateType ObjectType.
        /// </summary>
        public static readonly ExpandedNodeId IMachineTagNameplateType = new ExpandedNodeId(ObjectTypes.IMachineTagNameplateType, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the IMachineryItemVendorNameplateType ObjectType.
        /// </summary>
        public static readonly ExpandedNodeId IMachineryItemVendorNameplateType = new ExpandedNodeId(ObjectTypes.IMachineryItemVendorNameplateType, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the IMachineVendorNameplateType ObjectType.
        /// </summary>
        public static readonly ExpandedNodeId IMachineVendorNameplateType = new ExpandedNodeId(ObjectTypes.IMachineVendorNameplateType, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineryItemIdentificationType ObjectType.
        /// </summary>
        public static readonly ExpandedNodeId MachineryItemIdentificationType = new ExpandedNodeId(ObjectTypes.MachineryItemIdentificationType, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineIdentificationType ObjectType.
        /// </summary>
        public static readonly ExpandedNodeId MachineIdentificationType = new ExpandedNodeId(ObjectTypes.MachineIdentificationType, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineryComponentIdentificationType ObjectType.
        /// </summary>
        public static readonly ExpandedNodeId MachineryComponentIdentificationType = new ExpandedNodeId(ObjectTypes.MachineryComponentIdentificationType, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineComponentsType ObjectType.
        /// </summary>
        public static readonly ExpandedNodeId MachineComponentsType = new ExpandedNodeId(ObjectTypes.MachineComponentsType, Namespaces.Machinery);

    }
    #endregion

    #region ReferenceType Node Identifiers
    /// <summary>
    /// A class that declares constants for all ReferenceTypes in the Model.
    /// </summary>

    public static partial class ReferenceTypeIds
    {
    }
    #endregion

    #region Variable Node Identifiers
    /// <summary>
    /// A class that declares constants for all Variables in the Model.
    /// </summary>

    public static partial class VariableIds
    {
        /// <summary>
        /// The identifier for the IMachineTagNameplateType_Location Variable.
        /// </summary>
        public static readonly ExpandedNodeId IMachineTagNameplateType_Location = new ExpandedNodeId(Variables.IMachineTagNameplateType_Location, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the IMachineVendorNameplateType_ProductInstanceUri Variable.
        /// </summary>
        public static readonly ExpandedNodeId IMachineVendorNameplateType_ProductInstanceUri = new ExpandedNodeId(Variables.IMachineVendorNameplateType_ProductInstanceUri, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the IMachineryItemVendorNameplateType_InitialOperationDate Variable.
        /// </summary>
        public static readonly ExpandedNodeId IMachineryItemVendorNameplateType_InitialOperationDate = new ExpandedNodeId(Variables.IMachineryItemVendorNameplateType_InitialOperationDate, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the IMachineryItemVendorNameplateType_Manufacturer Variable.
        /// </summary>
        public static readonly ExpandedNodeId IMachineryItemVendorNameplateType_Manufacturer = new ExpandedNodeId(Variables.IMachineryItemVendorNameplateType_Manufacturer, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the IMachineryItemVendorNameplateType_MonthOfConstruction Variable.
        /// </summary>
        public static readonly ExpandedNodeId IMachineryItemVendorNameplateType_MonthOfConstruction = new ExpandedNodeId(Variables.IMachineryItemVendorNameplateType_MonthOfConstruction, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the IMachineryItemVendorNameplateType_SerialNumber Variable.
        /// </summary>
        public static readonly ExpandedNodeId IMachineryItemVendorNameplateType_SerialNumber = new ExpandedNodeId(Variables.IMachineryItemVendorNameplateType_SerialNumber, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the IMachineryItemVendorNameplateType_YearOfConstruction Variable.
        /// </summary>
        public static readonly ExpandedNodeId IMachineryItemVendorNameplateType_YearOfConstruction = new ExpandedNodeId(Variables.IMachineryItemVendorNameplateType_YearOfConstruction, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineryItemIdentificationType_AssetId Variable.
        /// </summary>
        public static readonly ExpandedNodeId MachineryItemIdentificationType_AssetId = new ExpandedNodeId(Variables.MachineryItemIdentificationType_AssetId, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineryItemIdentificationType_ComponentName Variable.
        /// </summary>
        public static readonly ExpandedNodeId MachineryItemIdentificationType_ComponentName = new ExpandedNodeId(Variables.MachineryItemIdentificationType_ComponentName, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineryItemIdentificationType_DeviceClass Variable.
        /// </summary>
        public static readonly ExpandedNodeId MachineryItemIdentificationType_DeviceClass = new ExpandedNodeId(Variables.MachineryItemIdentificationType_DeviceClass, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineryItemIdentificationType_HardwareRevision Variable.
        /// </summary>
        public static readonly ExpandedNodeId MachineryItemIdentificationType_HardwareRevision = new ExpandedNodeId(Variables.MachineryItemIdentificationType_HardwareRevision, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineryItemIdentificationType_InitialOperationDate Variable.
        /// </summary>
        public static readonly ExpandedNodeId MachineryItemIdentificationType_InitialOperationDate = new ExpandedNodeId(Variables.MachineryItemIdentificationType_InitialOperationDate, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineIdentificationType_DefaultInstanceBrowseName Variable.
        /// </summary>
        public static readonly ExpandedNodeId MachineIdentificationType_DefaultInstanceBrowseName = new ExpandedNodeId(Variables.MachineIdentificationType_DefaultInstanceBrowseName, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineIdentificationType_Location Variable.
        /// </summary>
        public static readonly ExpandedNodeId MachineIdentificationType_Location = new ExpandedNodeId(Variables.MachineIdentificationType_Location, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineIdentificationType_ProductInstanceUri Variable.
        /// </summary>
        public static readonly ExpandedNodeId MachineIdentificationType_ProductInstanceUri = new ExpandedNodeId(Variables.MachineIdentificationType_ProductInstanceUri, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineryComponentIdentificationType_DefaultInstanceBrowseName Variable.
        /// </summary>
        public static readonly ExpandedNodeId MachineryComponentIdentificationType_DefaultInstanceBrowseName = new ExpandedNodeId(Variables.MachineryComponentIdentificationType_DefaultInstanceBrowseName, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineryComponentIdentificationType_DeviceRevision Variable.
        /// </summary>
        public static readonly ExpandedNodeId MachineryComponentIdentificationType_DeviceRevision = new ExpandedNodeId(Variables.MachineryComponentIdentificationType_DeviceRevision, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineryItemIdentificationType_Manufacturer Variable.
        /// </summary>
        public static readonly ExpandedNodeId MachineryItemIdentificationType_Manufacturer = new ExpandedNodeId(Variables.MachineryItemIdentificationType_Manufacturer, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineryItemIdentificationType_ManufacturerUri Variable.
        /// </summary>
        public static readonly ExpandedNodeId MachineryItemIdentificationType_ManufacturerUri = new ExpandedNodeId(Variables.MachineryItemIdentificationType_ManufacturerUri, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineryItemIdentificationType_Model Variable.
        /// </summary>
        public static readonly ExpandedNodeId MachineryItemIdentificationType_Model = new ExpandedNodeId(Variables.MachineryItemIdentificationType_Model, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineryItemIdentificationType_MonthOfConstruction Variable.
        /// </summary>
        public static readonly ExpandedNodeId MachineryItemIdentificationType_MonthOfConstruction = new ExpandedNodeId(Variables.MachineryItemIdentificationType_MonthOfConstruction, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineryItemIdentificationType_ProductCode Variable.
        /// </summary>
        public static readonly ExpandedNodeId MachineryItemIdentificationType_ProductCode = new ExpandedNodeId(Variables.MachineryItemIdentificationType_ProductCode, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineryItemIdentificationType_ProductInstanceUri Variable.
        /// </summary>
        public static readonly ExpandedNodeId MachineryItemIdentificationType_ProductInstanceUri = new ExpandedNodeId(Variables.MachineryItemIdentificationType_ProductInstanceUri, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineryItemIdentificationType_SerialNumber Variable.
        /// </summary>
        public static readonly ExpandedNodeId MachineryItemIdentificationType_SerialNumber = new ExpandedNodeId(Variables.MachineryItemIdentificationType_SerialNumber, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineryItemIdentificationType_SoftwareRevision Variable.
        /// </summary>
        public static readonly ExpandedNodeId MachineryItemIdentificationType_SoftwareRevision = new ExpandedNodeId(Variables.MachineryItemIdentificationType_SoftwareRevision, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineryItemIdentificationType_YearOfConstruction Variable.
        /// </summary>
        public static readonly ExpandedNodeId MachineryItemIdentificationType_YearOfConstruction = new ExpandedNodeId(Variables.MachineryItemIdentificationType_YearOfConstruction, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineComponentsType_Component_Identification_Manufacturer Variable.
        /// </summary>
        public static readonly ExpandedNodeId MachineComponentsType_Component_Identification_Manufacturer = new ExpandedNodeId(Variables.MachineComponentsType_Component_Identification_Manufacturer, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineComponentsType_Component_Identification_SerialNumber Variable.
        /// </summary>
        public static readonly ExpandedNodeId MachineComponentsType_Component_Identification_SerialNumber = new ExpandedNodeId(Variables.MachineComponentsType_Component_Identification_SerialNumber, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the MachineComponentsType_DefaultInstanceBrowseName Variable.
        /// </summary>
        public static readonly ExpandedNodeId MachineComponentsType_DefaultInstanceBrowseName = new ExpandedNodeId(Variables.MachineComponentsType_DefaultInstanceBrowseName, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the Namespaces_http___opcfoundation_org_UA_Machinery__IsNamespaceSubset Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___opcfoundation_org_UA_Machinery__IsNamespaceSubset = new ExpandedNodeId(Variables.Namespaces_http___opcfoundation_org_UA_Machinery__IsNamespaceSubset, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the Namespaces_http___opcfoundation_org_UA_Machinery__NamespacePublicationDate Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___opcfoundation_org_UA_Machinery__NamespacePublicationDate = new ExpandedNodeId(Variables.Namespaces_http___opcfoundation_org_UA_Machinery__NamespacePublicationDate, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the Namespaces_http___opcfoundation_org_UA_Machinery__NamespaceUri Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___opcfoundation_org_UA_Machinery__NamespaceUri = new ExpandedNodeId(Variables.Namespaces_http___opcfoundation_org_UA_Machinery__NamespaceUri, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the Namespaces_http___opcfoundation_org_UA_Machinery__NamespaceVersion Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___opcfoundation_org_UA_Machinery__NamespaceVersion = new ExpandedNodeId(Variables.Namespaces_http___opcfoundation_org_UA_Machinery__NamespaceVersion, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the Namespaces_http___opcfoundation_org_UA_Machinery__StaticNodeIdTypes Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___opcfoundation_org_UA_Machinery__StaticNodeIdTypes = new ExpandedNodeId(Variables.Namespaces_http___opcfoundation_org_UA_Machinery__StaticNodeIdTypes, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the Namespaces_http___opcfoundation_org_UA_Machinery__StaticNumericNodeIdRange Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___opcfoundation_org_UA_Machinery__StaticNumericNodeIdRange = new ExpandedNodeId(Variables.Namespaces_http___opcfoundation_org_UA_Machinery__StaticNumericNodeIdRange, Namespaces.Machinery);

        /// <summary>
        /// The identifier for the Namespaces_http___opcfoundation_org_UA_Machinery__StaticStringNodeIdPattern Variable.
        /// </summary>
        public static readonly ExpandedNodeId Namespaces_http___opcfoundation_org_UA_Machinery__StaticStringNodeIdPattern = new ExpandedNodeId(Variables.Namespaces_http___opcfoundation_org_UA_Machinery__StaticStringNodeIdPattern, Namespaces.Machinery);

    }
    #endregion

    #region VariableType Node Identifiers
    /// <summary>
    /// A class that declares constants for all VariableType in the Model.
    /// </summary>

    public static partial class VariableTypeIds
    {
    }
    #endregion

    #region BrowseName Declarations
    /// <summary>
    /// Declares all of the BrowseNames used in the Model.
    /// </summary>
    public static partial class BrowseNames
    {
        /// <summary>
        /// The BrowseName for the <Component> component.
        /// </summary>
        public const string Component = "<Component>";
        /// <summary>
        /// The BrowseName for the IMachineTagNameplateType component.
        /// </summary>
        public const string IMachineTagNameplateType = "IMachineTagNameplateType";
        /// <summary>
        /// The BrowseName for the IMachineVendorNameplateType component.
        /// </summary>
        public const string IMachineVendorNameplateType = "IMachineVendorNameplateType";
        /// <summary>
        /// The BrowseName for the IMachineryItemVendorNameplateType component.
        /// </summary>
        public const string IMachineryItemVendorNameplateType = "IMachineryItemVendorNameplateType";
        /// <summary>
        /// The BrowseName for the Identification component.
        /// </summary>
        public const string Identification = "Identification";
        /// <summary>
        /// The BrowseName for the InitialOperationDate component.
        /// </summary>
        public const string InitialOperationDate = "InitialOperationDate";
        /// <summary>
        /// The BrowseName for the Location component.
        /// </summary>
        public const string Location = "Location";
        /// <summary>
        /// The BrowseName for the MachineComponentsType component.
        /// </summary>
        public const string MachineComponentsType = "MachineComponentsType";
        /// <summary>
        /// The BrowseName for the MachineIdentificationType component.
        /// </summary>
        public const string MachineIdentificationType = "MachineIdentificationType";
        /// <summary>
        /// The BrowseName for the MachineryComponentIdentificationType component.
        /// </summary>
        public const string MachineryComponentIdentificationType = "MachineryComponentIdentificationType";
        /// <summary>
        /// The BrowseName for the MachineryItemIdentificationType component.
        /// </summary>
        public const string MachineryItemIdentificationType = "MachineryItemIdentificationType";
        /// <summary>
        /// The BrowseName for the Machines component.
        /// </summary>
        public const string Machines = "Machines";
        /// <summary>
        /// The BrowseName for the MonthOfConstruction component.
        /// </summary>
        public const string MonthOfConstruction = "MonthOfConstruction";
        /// <summary>
        /// The BrowseName for the YearOfConstruction component.
        /// </summary>
        public const string YearOfConstruction = "YearOfConstruction";
        /// <summary>
        /// The BrowseName for the http://opcfoundation.org/UA/Machinery/ component.
        /// </summary>
        public const string http___opcfoundation_org_UA_Machinery_ = "http://opcfoundation.org/UA/Machinery/";
    }
    #endregion

    #region Namespace Declarations
    /// <summary>
    /// Defines constants for all namespaces referenced by the Model.
    /// </summary>
    public static partial class Namespaces
    {
        /// <summary>
        /// The URI for the OpcUa namespace (.NET code namespace is 'Opc.Ua').
        /// </summary>
        public const string OpcUa = "http://opcfoundation.org/UA/";

        /// <summary>
        /// The URI for the OpcUaXsd namespace (.NET code namespace is 'Opc.Ua').
        /// </summary>
        public const string OpcUaXsd = "http://opcfoundation.org/UA/2008/02/Types.xsd";

        /// <summary>
        /// The URI for the Machinery namespace.
        /// </summary>
        public const string Machinery = "http://opcfoundation.org/UA/Machinery/";

        /// <summary>
        /// The URI for the MachineryXsd namespace.
        /// </summary>
        public const string MachineryXsd = "http://opcfoundation.org/UA/Machinery/Types.xsd";
    }
    #endregion
}

